---

- name: Detect if docker compose is v2
  shell: docker compose
  failed_when: False
  register: compose_v2

- name: Set compose binary name
  set_fact:
    compose_bin: '{% if compose_v2.rc == 0 %}docker compose{% else %}docker-compose{% endif %}'
